name: Fix PHP code style issues

on: [push]

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.37.0
        with:
          php-version: '8.5'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@4.0.0

      - name: Run Laravel Pint
        run: vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: Fix styling
