name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.1, 8.2 ]
        laravel: [ 9.*, 10.* ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: cp phpunit.xml.dist phpunit.xml

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DOCUWARE_URL: ${{ secrets.DOCUWARE_URL }}
          DOCUWARE_USERNAME: ${{ secrets.DOCUWARE_USERNAME }}
          DOCUWARE_PASSWORD: ${{ secrets.DOCUWARE_PASSWORD }}
          DOCUWARE_COOKIES: ${{ secrets.DOCUWARE_COOKIES }}
          DOCUWARE_TESTS_FILE_CABINET_ID: ${{ secrets.DOCUWARE_TESTS_FILE_CABINET_ID }}
          DOCUWARE_TESTS_DIALOG_ID: ${{ secrets.DOCUWARE_TESTS_DIALOG_ID }}
          DOCUWARE_TESTS_BASKET_ID: ${{ secrets.DOCUWARE_TESTS_BASKET_ID }}
          DOCUWARE_TESTS_FIELD_NAME: ${{ secrets.DOCUWARE_TESTS_FIELD_NAME }}

          DOCUWARE_TESTS_DOCUMENT_FILE_SIZE_PREVIEW: ${{ secrets.DOCUWARE_TESTS_DOCUMENT_FILE_SIZE_PREVIEW }}
          DOCUWARE_TESTS_DOCUMENT_FILE_SIZE: ${{ secrets.DOCUWARE_TESTS_DOCUMENT_FILE_SIZE }}
          DOCUWARE_TESTS_DOCUMENTS_FILE_SIZE: ${{ secrets.DOCUWARE_TESTS_DOCUMENTS_FILE_SIZE }}
          DOCUWARE_TESTS_DOCUMENT_ID: ${{ secrets.DOCUWARE_TESTS_DOCUMENT_ID }}
          DOCUWARE_TESTS_DOCUMENTS_IDS: ${{ secrets.DOCUWARE_TESTS_DOCUMENTS_IDS }}
