name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.2, 8.3 ]
        laravel: [ 11.* ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: cp phpunit.xml.dist phpunit.xml

      - name: Migrate Config
        run: vendor/bin/pest --migrate-configuration

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DOCUWARE_URL: ${{ secrets.DOCUWARE_URL }}
          DOCUWARE_USERNAME: ${{ secrets.DOCUWARE_USERNAME }}
          DOCUWARE_PASSWORD: ${{ secrets.DOCUWARE_PASSWORD }}
          DOCUWARE_COOKIES: ${{ secrets.DOCUWARE_COOKIES }}

      - name: Store Log Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Store report artifacts
          path: ./vendor/orchestra/testbench-core/laravel/storage/logs
